### ISSUE TITLE
rnpm deprecated since react-native 0.60

### ISSUE THREAD

**Issue by loic-lopez** [unimonkiez/react-native-asset#22]
Hi!

rnpm will stop working from next release, the next configuration file will be `react-native.config.js`

**Reference:** [react-native-community/cli/blob/master/docs/configuration.md#migration-guide](https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide)

**Comment by unimonkiez** [comment]
Thanks for the heads up! should be an easy fix

**Comment by loic-lopez** [comment]
See: #23

**Comment by unimonkiez** [comment]
Merged, also published under version `2.0.0`

**Comment by loic-lopez** [comment]
There is a little bug with my commit if there is no `react-native.config.js`

this will throw an error:

```bash
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/loiclopez/app/android/react-native.config.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-asset/lib/cli.js:44:27)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by unimonkiez** [comment]
you should run `react-native-asset` inside the root of the project, it seems you run it inside of the android folder

**Comment by loic-lopez** [comment]
Yes it's ok

**Comment by unimonkiez** [comment]
Cool! Thank you for your contribution!
