### ISSUE TITLE
global install of react-native-asset breaks metro bundler

### ISSUE THREAD

**Issue by brianephraim** [unimonkiez/react-native-asset#31]
After running `npm install react-native-asset -g`, and then running `react-native start --reset-cache`, and then starting my iOS simulator, I get an error in the bundler terminal and also in the simulator:
```my-app
error: bundling failed: Error: Unable to resolve module `./../../../../../../usr/local/lib/node_modules/react-native/node_modules/react-transform-hmr/lib/index.js` from `/Users/me/Sites/my-app/app/appEntry/appEntry.js`: The module `./../../../../../../usr/local/lib/node_modules/react-native/node_modules/react-transform-hmr/lib/index.js` could not be found from `/Users/me/Sites/my-app/app/appEntry/appEntry.js`. Indeed, none of these files exist:
  * `/usr/local/lib/node_modules/react-native/node_modules/react-transform-hmr/lib/index.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/usr/local/lib/node_modules/react-native/node_modules/react-transform-hmr/lib/index.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/usr/local/lib/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/usr/local/lib/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/usr/local/lib/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/usr/local/lib/node_modules/react-native/node_modules/metro/src/lib/transformHelpers.js:264:42)
    at /usr/local/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31
    at Array.map (<anonymous>)
    at resolveDependencies (/usr/local/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /usr/local/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/usr/local/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```

In order to fix this,  
`npm uninstall react-native-asset`  
`npm install react-native-cli`  
and to further clean things up
`npm uninstall react -g`

I'm guessing the problem is with package.json including
```
"peerDependencies": {
    "react-native": "^0.60.0"
  },
```

I can still use `react-native-asset` as a non-global install, and call it like `./node_modules/.bin/react-native-asset`.

**Comment by unimonkiez** [comment]
Shouldn't be used with global install, closing
