### ISSUE TITLE
Cannot find module 'react-native/local-cli/link/ios/createGroupWithMessage'

### ISSUE THREAD

**Issue by hmontes** [unimonkiez/react-native-asset#4]
Hi. I have an issue.

```
react-native-asset
module.js:557
    throw err;
    ^

Error: Cannot find module 'react-native/local-cli/link/ios/createGroupWithMessage'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/Datos/hmontes/.config/yarn/global/node_modules/react-native-asset/lib/copy-assets/ios.js:4:32)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

Can you help me, please?

Thank you

**Comment by unimonkiez** [comment]
How did you install `react-native-asset`? yarn or npm? global or not?

Guessing you installed globally, using npm, please run `npm -g ls` just so I can see what deps and versions are installed.

**Comment by hmontes** [comment]
You are wrong. I'm installed react-native-asset with yarn (yarn global add react-native-asset)

yarn global list
```
warning " > react-native-asset@1.0.2" has unmet peer dependency "react-native@^0.52.1".
info "@storybook/cli@3.3.13" has binaries:
   - getstorybook
info "apidoc@0.17.6" has binaries:
   - apidoc
info "nodemon@1.15.1" has binaries:
   - nodemon
info "react-native-asset@1.0.2" has binaries:
   - react-native-asset
info "react-native-cli@2.0.1" has binaries:
   - react-native
info "react-native-git-upgrade@0.2.7" has binaries:
   - react-native-git-upgrade
✨  Done in 3.05s.
```

**Comment by hmontes** [comment]
Btw, I created the project yesterday, so, the react-native version is 0.54.0

**Comment by BrodaNoel** [comment]
Same problem here.
I installed this app by running `sudo npm i -g react-native-asset`

**Comment by BrodaNoel** [comment]
```
➜  app git:(migration) ✗ npm ls -g --depth=0
/usr/local/lib
├── create-react-app@1.5.2
├── firebase-tools@3.17.4
├── http-server@0.11.1
├── node-gyp@3.6.2
├── npm@5.6.0
├── UNMET PEER DEPENDENCY react-native@^0.52.1
├── react-native-asset@1.0.2
└── react-native-cli@2.0.1
```

**Comment by BrodaNoel** [comment]
This is the workaround:
`react-native-asset` is looking for the global `react-native` dependency.
Just run `npm install -g react-native` and it's going to be there.
Then, in the future, after this big is fixed, you can remove that global dependency.

**Comment by unimonkiez** [comment]
Made `react-native` a normal dependency instead of a peer one.  
making peer dependencies for cli-tools is kindof funky, all good now.
